name: Build Project

on:
  push:
    branches:
      - main    # ou a branch que você quiser monitorar
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # ou 16, conforme sua necessidade

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
